name: Canned Rsync
  
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: nottotouchthesun_net/doorsinpoetryandhistory/dist/
        remote_host: kontar.kattare.com
        remote_user: cbalzpersonal
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
