name: Deploy Website
  
on:
  push:
    branches:
    - main
  workflow_dispatch:
      branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --exclude '.git*'
        path: ./
        remote_path: nottotouchthesun_net/doorsinpoetryandhistory/
        remote_host: kontar.kattare.com
        remote_user: cbalzpersonal
        remote_key: ${{ secrets.NOTTOTOUCHTHESUN }}
        
